import Head from 'next/head'
import React from 'react'
import BottomHeader from '../components/BottomHearder'
import TopHeader from '../components/TopHeader'
import { useSelector } from 'react-redux';
import CartProduct from '../components/CartProduct';

function Cart() {

    const products = useSelector(state => state.cart.products);
    let subtotal = 0;
    let totalQty = 0

    products.map(({ price, qty }) => {
        subtotal = subtotal + (price * qty)
        totalQty = totalQty + qty
    })



    return (
        <div className='bg-gray-200'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopHeader />
            <BottomHeader />
            <div className='container mx-auto lg:flex lg:flex-row'>
                <div className='my-2 mr-2 basis-4/5' >
                    <div className='my-2'>
                        <img className='' src="https://images-eu.ssl-images-amazon.com/images/G/31/Biss_2022/Headers/HSSDec/HSSDecauto/HSSLogo/HSS_1500x300-PC.jpg" alt="banner" />
                    </div>
                    <div className='bg-white p-4 shadow-sm'>
                        <p className='text-2xl font-semibold border-b-2 py-3'>{products.length == 0 ? "Your Cart is Empty" : "Your Cart Items"}</p>
                        {products.map(({ id, title, image, price, category, rating, description, qty }) => (
                            <CartProduct
                                key={Math.random()}
                                id={id}
                                title={title}
                                image={image}
                                price={price}
                                category={category}
                                rating={rating}
                                description={description}
                                qty={qty}
                            />
                        ))
                        }
                    </div>
                </div>
                <div className='bg-white p-4 my-2 mt-4 shadow-sm basis-1/5'>
                    <p className='text-center mb-3'>Subtotal ( <span className='font-bold'>{totalQty}</span> items ) : <span className='font-bold'>₹ {subtotal.toFixed(2)}</span> </p>
                    <button className='font-semibold mt-auto p-2 text-xs from-yellow-200 to-yellow-400  rounded-sm border border-yellow-300 md:text-sm bg-gradient-to-b hover:bg-yellow-500 w-full focus:outline-none focus:ring-2 focus:ring-yellow-500 active:from-yellow-500'>Proceed to Checkout</button>
                </div>
            </div>
        </div>
    )
}

export default Cart