import Head from "next/head";
import Router from "next/router";
import BottomHeader from "../components/BottomHearder";
import Hearder from "../components/BottomHearder";
import HomeCarousel from "../components/HomeCarousel";
import Products from "../components/Products";
import TopHeader from "../components/TopHeader";
import Filter from "../components/Filter";

export default function Home({ products }) {
  return (
    <div className="bg-gray-200">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopHeader />
      <BottomHeader />
      <div className="container mx-auto">
        <HomeCarousel />
        <div className="flex flex-row">
          <Filter products={products} />
          <Products products={products} />
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );
  // console.log(products)
  return {
    props: {
      products,
    }, // will be passed to the page component as props
  };
}
